# Generated by Django 5.0.6 on 2024-06-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_experiences',
            field=models.ManyToManyField(to='myportfolio.jobexperience'),
        ),
    ]
