# Generated by Django 5.0.6 on 2024-06-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_remove_course_end_date_remove_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_experiences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myportfolio.jobexperience'),
        ),
    ]
