# Generated by Django 5.0.6 on 2024-06-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_alter_user_job_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
