# Generated by Django 5.0.6 on 2024-06-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_alter_projects_live_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
