# Generated by Django 5.0.6 on 2024-06-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_rename_projects_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_flows',
        ),
        migrations.DeleteModel(
            name='WorkFlow',
        ),
    ]
