# Generated by Django 5.0.6 on 2024-06-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_remove_user_work_flows_delete_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_experiences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='myportfolio.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='educations',
            field=models.ManyToManyField(to='myportfolio.education'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(to='myportfolio.interest'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_experiences',
            field=models.ManyToManyField(blank=True, null=True, to='myportfolio.jobexperience'),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(to='myportfolio.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(to='myportfolio.skill'),
        ),
    ]
